apiVersion: v1
kind: Service
metadata:
  name: simple-flask-app
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    app: simple-flask-app
spec:
  type: {{ .Values.service.type | quote }}
  selector:
    app: simple-flask-app
  ports:
  - port: {{ .Values.service.port | int }}
    targetPort: {{ .Values.service.targetPort | int }}
