name: My First Workflow
# This is the title of your workflow. When you look at the Actions tab in your GitHub repository, this is the name you will see.

on: push
# This is the trigger. It tells GitHub exactly when to run this workflow. In this case, it will run automatically every time someone pushes new code to the repository.

jobs:
# A workflow is made up of one or more jobs. Jobs run in parallel by default, but this file only has one.
  first_job:
   #This is just the ID or name given to this specific job.

    runs-on: ubuntu-latest
    # This tells GitHub what kind of virtual machine (server) to use to run your job. Here, it's requesting the latest version of the Ubuntu Linux operating system.

    steps:
    # The steps section is a sequence of tasks executed in order on the Ubuntu server.
      - name: Checkout Repository
        # this is the name of step in the job
        uses: actions/checkout@v4
        # This is a crucial pre-built action. By default, the virtual machine starts empty. This action downloads a copy of your repository's code onto the server so that the following steps can interact with your files.

      - name: Welcome message
        run: echo "My first GitHub Actions Job"

      - name: List files
        run: ls

      - name: Read file
        run: cat README.md


# Whenever you push code to your repository, GitHub will spin up a fresh Linux server, download your code onto it, print a welcome message, list the files in your project, and finally print the contents of your README.md file.